config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  get 'admin/student_list'
  get 'admin/fee_process'
  get 'admin/attendance'
  resources :posts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/index'
  get 'home/dashboard'
  get 'home/gallery'
  get 'home/fee'
  get 'home/books'
  get 'home/contact_us'
  get 'home/about'
  root 'home#index'
  get 'home/gallery'
  get 'home/fee'
  get 'home/books'
  get 'home/contect_us'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :username, presence: true
         devise :database_authenticatable, :authentication_keys => [:username]
         validates :username, uniqueness: true
         has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/user.png"
         validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end

  def student_list
  end

  def fee_process
  end

  def attendance
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:student_name, :guardian_name, :username,:date_of_birth, :is_female, :phone, :skype_id, :country, :state, :city,  :morning, :day, :evning, :email, :password, :password_confirmation, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:student_name, :guardian_name, :username, :date_of_birth, :is_female, :phone, :skype_id, :country, :state, :city,  :morning, :day, :evning, :avatar])
  end

  def create
  @user = User.create(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
  end

  def gallery
  end

  def fee
  end

  def books
  end

  def contact_us
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/attendance.html.erb
<h1>Admin#attendance</h1>
<p>Find me in app/views/admin/attendance.html.erb</p>

app/views/admin/dashboard.html.erb
<div class="theme-cyan">
  <div id="wrapper">
    <!-- <nav class="navbar navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-btn">
          <button type="button" class="btn-toggle-offcanvas">
            <i class="lnr lnr-menu fa fa-bars"></i>
          </button>
        </div>
        <div class="navbar-brand">
          <%# <%= link_to 'KalamEpak', root_path, style:'font-weight:bold' %> %>
        </div>
        <div class="navbar-right">
          <div id="navbar-menu">
            <ul class="nav navbar-nav">
              <li>
                <a href="app-inbox.html" class="icon-menu d-none d-sm-block">
                  <i class="icon-envelope"></i>
                  <span class="notification-dot"></span></a>
              </li>
              <li>
                <%# <%= link_to destroy_user_session_path, method: :delete do %> %>
                <i class="icon-login fa-lg" style="color:gray"></i>
              <%# <% end %> %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav> -->

  <div id="left-sidebar" class="sidebar">
    <div class="sidebar-scroll">
      <div class="user-account">
        <%= image_tag(current_user.avatar.url(:thumb), class: "rounded-circle user-photo", alt: "User Profile Picture") %>
          <div class="dropdown">
            <span>Welcome,</span><br>
            <% @users = User.all  %>
              <strong class="dropdown-toggle user-name" data-toggle="dropdown"><%= current_user.username %></strong>
              <ul class="dropdown-menu dropdown-menu-right account">
                <li><%= link_to edit_user_registration_path, class: "icon-user" do %>
                  <i></i>My Profile
                <%end%>
              </li>
              <!-- <li><a href="doctor-profile.html"><i class="icon-user"></i>My Profile</a></li> -->
              <li>
                <a href="app-inbox.html">
                  <i class="icon-envelope-open"></i>Messages</a>
              </li>
              <li>
                <a href="javascript:void(0);">
                  <i class="icon-settings"></i>Settings</a>
              </li>
              <li class="divider"></li>
              <li><%= link_to destroy_user_session_path, method: :delete, class: "icon-power" do %>
                <i></i>Logout
              <% end %>
            </li>
          </ul>
        </div>
        <hr>
      </div>
          <!-- Tab panes -->
          <div class="tab-content p-l-0 p-r-0">
            <div class="tab-pane active" id="menu">
              <nav class="sidebar-nav">
                <ul class="main-menu metismenu">
                  <li><%= link_to root_path do %>
                    <i class="icon-home"></i>
                    <span>Dashboard</span>
                  <% end %>
                </li>
                <li>
                  <a href="javascript:void(0);">
                    <i class="icon-wallet"></i>
                    <span>Student List</span>
                  </a>
                  <ul></ul>
                </li>
                <li>
                  <a href="javascript:void(0);">
                    <i class="icon-user"></i>
                    <span>Attendance</span>
                  </a>
                  <ul></ul>
                </li>
                <li>
                  <a href="javascript:void(0);">
                    <i class="icon-user-follow"></i>
                    <span>fee Process</span>
                  </a>
                  <ul></ul>
                </li>
                <li>
                  <a href="javascript:void(0);">
                    <i class="icon-user-following"></i>
                    <span>Books</span>
                  </a>
                </li>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/fee_process.html.erb
<h1>Admin#fee_process</h1>
<p>Find me in app/views/admin/fee_process.html.erb</p>

app/views/admin/student_list.html.erb
<h1>Admin#student_list</h1>
<p>Find me in app/views/admin/student_list.html.erb</p>

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
      <%= link_to 'Kalamepak', root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Gallery', home_gallery_path %></li>
      <li><%= link_to 'Fee', home_fee_path %></li>
      <li><%= link_to 'Books', home_books_path %></li>
      <li><%= link_to 'Contact Us', home_contact_us_path %></li>
      <li><%= link_to 'About', home_about_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", user_session_path %></li>
        <li><%= link_to "Join", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/books.html.erb
<h1>Home#books</h1>
<p>Find me in app/views/home/books.html.erb</p>

app/views/home/contact_us.html.erb
<h1>Home#contact_us</h1>
<p>Find me in app/views/home/contact_us.html.erb</p>

app/views/home/fee.html.erb
<h1>Home#fee</h1>
<p>Find me in app/views/home/fee.html.erb</p>

app/views/home/gallery.html.erb
<h1>Home#gallery</h1>
<p>Find me in app/views/home/gallery.html.erb</p>

app/views/home/index.html.erb
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-title">Nav Title</li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="nav-icon cui-speedometer"></i> Nav item
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="nav-icon cui-speedometer"></i> With badge
          <span class="badge badge-primary">NEW</span>
        </a>
      </li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon cui-puzzle"></i> Nav dropdown
        </a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="nav-icon cui-puzzle"></i> Nav dropdown item
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="nav-icon cui-puzzle"></i> Nav dropdown item
            </a>
          </li>
        </ul>
      </li>
      <li class="nav-item mt-auto">
        <a class="nav-link nav-link-success" href="https://coreui.io">
          <i class="nav-icon cui-cloud-download"></i> Download CoreUI</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-danger" href="https://coreui.io/pro/">
          <i class="nav-icon cui-layers"></i> Try CoreUI
          <strong>PRO</strong>
        </a>
      </li>
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

app/views/home/sidebar.html.erb
<h1>hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalamepak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%# if user_signed_in? %>
  <%#redirect root_a %>

  <%# render 'admin/dashboard' %>
  <%# elsif %>
  <%= render 'home/header' %>
  <%# end %>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>